### ISSUE TITLE
Reconhecer uma entrada informada com a tabela preditiva tabular

### ISSUE THREAD

**Issue by mfelipek** [mfelipe-eisenkraemer/compiler_parser#5]
Exibir a pilha de derivação do símbolo de início até o reconhecimento ou não, da entrada informada.

**Comment by henriquels25** [comment]
Desenvolvi a funcionalidade, testa ai Mateus pra ver se esta funcionando.

**Comment by mfelipek** [comment]
Testei com algumas gramáticas e funcionou. Ficou muito bom.
